# Generated by Django 3.2.14 on 2022-07-23 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0002_alter_customuser_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='measure_unity',
        ),
        migrations.AddField(
            model_name='product',
            name='expiry_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='manufacture_date',
            field=models.DateTimeField(null=True),
        ),
    ]
