# Generated by Django 3.2.14 on 2022-07-23 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0003_auto_20220723_0833'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Product',
            new_name='Medicine',
        ),
        migrations.AlterModelTable(
            name='medicine',
            table='Medicine',
        ),
    ]
