# Generated by Django 3.2.14 on 2022-07-27 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0004_auto_20220723_0909'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='medicine',
            table='medicine',
        ),
    ]
