# Generated by Django 3.2.14 on 2022-08-05 21:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0005_alter_medicine_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Requests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('status', models.CharField(choices=[('PENDING', 'PENDING'), ('APROVED', 'APROVED'), ('DENIED', 'DENIED')], default='PENDING', max_length=15)),
                ('return_date', models.DateTimeField(null=True)),
                ('hospital_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner_hospital', to='medical.hospital')),
                ('hospital_requested', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requested_hospital', to='medical.hospital')),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medical.medicine')),
            ],
            options={
                'db_table': 'request',
            },
        ),
    ]
