# Generated by Django 3.2.14 on 2022-08-07 16:19

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0006_requests'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='expiry_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 7, 16, 19, 18, 872186, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='manufacture_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 7, 16, 19, 18, 872186, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='requests',
            name='return_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 7, 16, 19, 18, 872186, tzinfo=utc)),
        ),
    ]
