# Generated by Django 3.2.14 on 2022-08-08 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0007_auto_20220807_1819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='expiry_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='manufacture_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='requests',
            name='return_date',
            field=models.DateTimeField(null=True),
        ),
    ]
