# Generated by Django 3.2.14 on 2022-08-16 07:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0008_auto_20220808_0838'),
    ]

    operations = [
        migrations.CreateModel(
            name='Approved',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('status', models.CharField(choices=[('PENDING', 'PENDING'), ('APROVED', 'APROVED'), ('DENIED', 'DENIED')], default='APROVED', max_length=15)),
                ('return_date', models.DateTimeField(null=True)),
                ('hospital_approved', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approved_hospital', to='medical.hospital')),
                ('hospital_requested', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='request_hospital', to='medical.hospital')),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medical.medicine')),
            ],
            options={
                'db_table': 'approved',
            },
        ),
    ]
