# Generated by Django 3.2.14 on 2022-08-17 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0009_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approved',
            name='status',
            field=models.CharField(choices=[('PENDING', 'PENDING'), ('APPROVED', 'APPROVED'), ('DENIED', 'DENIED')], default='APPROVED', max_length=15),
        ),
        migrations.AlterField(
            model_name='requests',
            name='status',
            field=models.CharField(choices=[('PENDING', 'PENDING'), ('APPROVED', 'APPROVED'), ('DENIED', 'DENIED')], default='PENDING', max_length=15),
        ),
    ]
