# Generated by Django 3.2.14 on 2022-08-20 20:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0010_auto_20220817_2115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='expiry_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='manufacture_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
