# Generated by Django 3.2.14 on 2022-08-28 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0012_auto_20220827_1345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='expiry_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='manufacture_date',
            field=models.DateTimeField(null=True),
        ),
    ]
