# Generated by Django 3.2.14 on 2022-09-04 08:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0013_auto_20220828_1646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approved',
            name='status',
            field=models.CharField(choices=[('PENDING', 'PENDING'), ('APPROVED', 'APPROVED'), ('DENIED', 'DENIED'), ('RETURNED', 'RETURNED')], default='APPROVED', max_length=15),
        ),
        migrations.AlterField(
            model_name='requests',
            name='status',
            field=models.CharField(choices=[('PENDING', 'PENDING'), ('APPROVED', 'APPROVED'), ('DENIED', 'DENIED'), ('RETURNED', 'RETURNED')], default='PENDING', max_length=15),
        ),
        migrations.CreateModel(
            name='Returned',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('status', models.CharField(choices=[('PENDING', 'PENDING'), ('APPROVED', 'APPROVED'), ('DENIED', 'DENIED'), ('RETURNED', 'RETURNED')], default='PENDING', max_length=15)),
                ('return_date', models.DateTimeField(null=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('hospital_received', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recieved_hospital', to='medical.hospital')),
                ('hospital_returned', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='returned_hospital', to='medical.hospital')),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medical.medicine')),
            ],
            options={
                'db_table': 'returned',
            },
        ),
    ]
